global: 
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'localhost:9090' 
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 15s

  - job_name: 'backend'
    static_configs:
      - targets:
        - 'backend:8000'
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 8s

  - job_name: 'frontend_http_probe'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - 'http://frontend:3000' 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080' 
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 8s

  - job_name: 'loki'
    static_configs:
      - targets:
        - 'loki:3100'  
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 8s

  - job_name: 'alertmanager'
    static_configs:
      - targets:
        - 'alertmanager:9093' 
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 8s

  - job_name: 'postgres'
    static_configs:
      - targets:
        - 'postgres_exporter:9187' 
    metrics_path: /metrics
    scrape_interval: 20s
    scrape_timeout: 15s